import { Pressable, Text, View } from "react-native";
import { router } from "expo-router";
import { useQuery } from "@tanstack/react-query";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { portal } from "@/lib/portal";

export default function BusinessSettingsScreen() {
  const colors = useColors();
  const context = useQuery({ queryKey: ["tenant-context"], queryFn: portal.tenantContext });
  const tenant = context.data?.tenant;
  const membership = context.data?.membership;
  return <ScreenContainer className="px-4 pt-4"><View className="flex-row items-center mb-6"><Pressable onPress={() => router.back()} style={({ pressed }) => [{ width: 40, height: 40, borderRadius: 20, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" }, pressed && { opacity: 0.7 }]}><IconSymbol name="arrow.left" size={21} color={colors.foreground} /></Pressable><View className="ml-3"><Text style={{ color: colors.foreground, fontSize: 24, fontWeight: "900" }}>Business Settings</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 2 }}>Live tenant configuration</Text></View></View><View style={{ borderRadius: 22, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, padding: 18, marginBottom: 14 }}><Text style={{ color: colors.muted, fontSize: 11, fontWeight: "800", letterSpacing: 0.8 }}>BUSINESS PROFILE</Text><Text style={{ color: colors.foreground, fontSize: 21, fontWeight: "900", marginTop: 8 }}>{tenant?.name ?? "Loading business…"}</Text><View className="flex-row justify-between mt-5"><View><Text style={{ color: colors.muted, fontSize: 12 }}>Currency</Text><Text style={{ color: colors.foreground, fontSize: 15, fontWeight: "800", marginTop: 4 }}>{tenant?.currency ?? "—"}</Text></View><View><Text style={{ color: colors.muted, fontSize: 12 }}>Tenant ID</Text><Text style={{ color: colors.foreground, fontSize: 15, fontWeight: "800", marginTop: 4 }}>{tenant?.id ?? "—"}</Text></View></View></View><View style={{ borderRadius: 22, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, padding: 18 }}><View className="flex-row items-center"><View style={{ width: 38, height: 38, borderRadius: 19, backgroundColor: "#E6F6F7", alignItems: "center", justifyContent: "center" }}><IconSymbol name="adjustments" size={19} color={colors.primary} /></View><View className="ml-3"><Text style={{ color: colors.foreground, fontWeight: "900", fontSize: 16 }}>Workspace access</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 2 }}>Permission from portal</Text></View></View><View style={{ height: 1, backgroundColor: colors.border, marginVertical: 16 }} /><Text style={{ color: colors.muted, fontSize: 12 }}>Current role</Text><Text style={{ color: colors.foreground, fontWeight: "800", marginTop: 4 }}>{membership?.role ?? "Loading…"}</Text><Text style={{ color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 15 }}>Business profile and permission changes are controlled by the live OmniPOS portal. This mobile view reflects the current tenant configuration without creating a separate local copy.</Text></View></ScreenContainer>;
}
