import { useMemo, useState } from "react";
import { Alert, FlatList, Pressable, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { useMutation, useQuery } from "@tanstack/react-query";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { portal } from "@/lib/portal";
import { money, type PaymentMethod } from "@/shared/omnipos";
import { useCart } from "@/lib/cart-context";

export default function CheckoutScreen() {
  const colors = useColors(); const cart = useCart(); const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>("cash"); const [received, setReceived] = useState(String(cart.total)); const [customerId, setCustomerId] = useState<number | null>(null);
  const customers = useQuery({ queryKey: ["customers", "checkout"], queryFn: () => portal.customers() });
  const checkout = useMutation({ mutationFn: () => portal.checkout({ items: cart.lines.map((line) => ({ productId: line.id, quantity: line.quantity, price: line.price })), customerId, paymentMethod, amountReceived: Number(received) || 0, discountTotal: 0, taxTotal: 0 }), onSuccess: (result) => { cart.clear(); router.replace({ pathname: "/checkout-success", params: { orderNumber: result.orderNumber, total: String(result.total), changeDue: String(result.changeDue), points: String(result.loyaltyPointsEarned) } }); }, onError: (error) => Alert.alert("Checkout failed", error.message) });
  const change = Math.max((Number(received) || 0) - cart.total, 0);
  const canSubmit = cart.lines.length > 0 && (paymentMethod !== "cash" || Number(received) >= cart.total);
  return <ScreenContainer className="px-4 pt-3" edges={["top", "left", "right", "bottom"]}><View className="flex-row items-center mb-5"><Pressable onPress={() => router.back()} className="mr-3" style={({ pressed }) => [pressed && { opacity: 0.6 }]}><IconSymbol name="arrow.left" size={24} color={colors.foreground} /></Pressable><Text className="text-2xl font-bold text-foreground">Review order</Text></View>
    <FlatList data={cart.lines} keyExtractor={(item) => String(item.id)} contentContainerStyle={{ gap: 12, paddingBottom: 20 }} renderItem={({ item }) => <View className="flex-row items-center rounded-2xl bg-surface border border-border p-3"><View className="flex-1"><Text className="font-semibold text-foreground">{item.name}</Text><Text className="text-sm text-muted">{item.quantity} × {money(item.price)}</Text></View><View className="flex-row items-center"><Pressable onPress={() => cart.decrement(item.id)} style={({ pressed }) => [{ width: 32, height: 32, borderRadius: 16, backgroundColor: colors.background, alignItems: "center", justifyContent: "center" }, pressed && { opacity: 0.6 }]}><IconSymbol name="minus" size={18} color={colors.foreground} /></Pressable><Text className="font-semibold text-foreground mx-3">{item.quantity}</Text><Pressable onPress={() => cart.add(item)} style={({ pressed }) => [{ width: 32, height: 32, borderRadius: 16, backgroundColor: colors.surface, alignItems: "center", justifyContent: "center" }, pressed && { opacity: 0.6 }]}><IconSymbol name="plus" size={18} color={colors.primary} /></Pressable></View></View>} ListEmptyComponent={<Text className="text-muted">Your cart is empty.</Text>} />
    <View className="rounded-2xl bg-surface border border-border p-4 mb-3"><Text className="font-semibold text-foreground mb-3">Customer (optional)</Text><FlatList horizontal showsHorizontalScrollIndicator={false} data={customers.data ?? []} keyExtractor={(item) => String(item.id)} contentContainerStyle={{ gap: 8 }} renderItem={({ item }) => <Pressable onPress={() => setCustomerId(item.id)} style={{ paddingHorizontal: 12, paddingVertical: 8, borderRadius: 16, backgroundColor: customerId === item.id ? colors.primary : colors.background }}><Text style={{ color: customerId === item.id ? "#fff" : colors.foreground }}>{item.name}</Text></Pressable>} /></View>
    <View className="rounded-2xl bg-surface border border-border p-4 mb-3"><Text className="font-semibold text-foreground mb-3">Payment method</Text><View className="flex-row flex-wrap gap-2">{(["cash", "card", "transfer", "other"] as PaymentMethod[]).map((method) => <Pressable key={method} onPress={() => setPaymentMethod(method)} style={{ paddingHorizontal: 14, paddingVertical: 9, borderRadius: 18, backgroundColor: paymentMethod === method ? colors.primary : colors.background }}><Text style={{ color: paymentMethod === method ? "#fff" : colors.foreground, textTransform: "capitalize" }}>{method}</Text></Pressable>)}</View>{paymentMethod === "cash" && <TextInput value={received} onChangeText={setReceived} keyboardType="decimal-pad" placeholder="Amount received" placeholderTextColor={colors.muted} className="mt-3 h-12 rounded-xl bg-background px-3 text-foreground" />}</View>
    <View className="flex-row justify-between mb-3"><Text className="text-base text-muted">Total</Text><Text className="text-xl font-bold text-foreground">{money(cart.total)}</Text></View>{paymentMethod === "cash" && <View className="flex-row justify-between mb-3"><Text className="text-base text-muted">Change due</Text><Text className="text-base font-semibold" style={{ color: change > 0 ? colors.primary : colors.muted }}>{money(change)}</Text></View>}
    <Pressable disabled={!canSubmit || checkout.isPending} onPress={() => checkout.mutate()} style={({ pressed }) => [{ height: 54, borderRadius: 16, backgroundColor: canSubmit ? colors.primary : colors.border, alignItems: "center", justifyContent: "center" }, pressed && canSubmit && { opacity: 0.86 }]}><Text className="text-white font-bold text-base">{checkout.isPending ? "Processing…" : "Complete sale"}</Text></Pressable>
  </ScreenContainer>;
}
