import { useState } from "react";
import { Alert, FlatList, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { portal } from "@/lib/portal";
import { money, type PaymentMethod } from "@/shared/omnipos";
import { useCart } from "@/lib/cart-context";

export default function CheckoutScreen() {
  const colors = useColors();
  const cart = useCart();
  const client = useQueryClient();
  const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>("cash");
  const [received, setReceived] = useState(String(cart.total));
  const [customerId, setCustomerId] = useState<number | null>(null);
  const customers = useQuery({ queryKey: ["customers", "checkout"], queryFn: () => portal.customers() });
  const checkout = useMutation({ mutationFn: () => portal.checkout({ items: cart.lines.map((line) => ({ productId: line.id, quantity: line.quantity, price: line.price })), customerId, paymentMethod, amountReceived: Number(received) || 0, discountTotal: 0, taxTotal: 0 }), onSuccess: (result) => { client.invalidateQueries({ queryKey: ["products"] }); client.invalidateQueries({ queryKey: ["inventory"] }); client.invalidateQueries({ queryKey: ["customers"] }); client.invalidateQueries({ queryKey: ["sales"] }); cart.clear(); router.replace({ pathname: "/checkout-success", params: { orderNumber: result.orderNumber, total: String(result.total), changeDue: String(result.changeDue), points: String(result.loyaltyPointsEarned) } }); }, onError: (error) => Alert.alert("Checkout failed", error.message) });
  const change = Math.max((Number(received) || 0) - cart.total, 0);
  const canSubmit = cart.lines.length > 0 && (paymentMethod !== "cash" || Number(received) >= cart.total);
  const methods: PaymentMethod[] = ["cash", "card", "transfer", "other"];

  return <ScreenContainer className="px-4 pt-3" edges={["top", "left", "right", "bottom"]}><View className="flex-row items-center mb-5"><Pressable onPress={() => router.back()} style={({ pressed }) => [{ width: 38, height: 38, borderRadius: 19, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center", marginRight: 11 }, pressed && { opacity: 0.6 }]}><IconSymbol name="arrow.left" size={21} color={colors.foreground} /></Pressable><Text style={{ color: colors.foreground, fontSize: 24, fontWeight: "900", letterSpacing: -0.5 }}>Review order</Text></View>
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 20 }}>
      <FlatList scrollEnabled={false} data={cart.lines} keyExtractor={(item) => String(item.id)} contentContainerStyle={{ gap: 10 }} renderItem={({ item }) => <View style={{ flexDirection: "row", alignItems: "center", borderRadius: 18, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, padding: 14 }}><View className="flex-1"><Text style={{ color: colors.foreground, fontWeight: "800", fontSize: 15 }}>{item.name}</Text><Text style={{ color: colors.muted, fontSize: 13, marginTop: 4 }}>{item.quantity} × {money(item.price)}</Text></View><View style={{ flexDirection: "row", alignItems: "center" }}><Pressable onPress={() => cart.decrement(item.id)} style={({ pressed }) => [{ width: 31, height: 31, borderRadius: 16, backgroundColor: colors.background, alignItems: "center", justifyContent: "center" }, pressed && { opacity: 0.6 }]}><IconSymbol name="minus" size={17} color={colors.foreground} /></Pressable><Text style={{ color: colors.foreground, fontWeight: "800", marginHorizontal: 12 }}>{item.quantity}</Text><Pressable onPress={() => cart.add(item)} style={({ pressed }) => [{ width: 31, height: 31, borderRadius: 16, backgroundColor: "#E8F7F3", alignItems: "center", justifyContent: "center" }, pressed && { opacity: 0.6 }]}><IconSymbol name="plus" size={17} color={colors.primary} /></Pressable></View></View>} ListEmptyComponent={<Text className="text-muted">Your cart is empty.</Text>} />
      <View style={{ borderRadius: 20, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, padding: 16, marginTop: 16 }}><Text style={{ color: colors.foreground, fontSize: 16, fontWeight: "900", marginBottom: 12 }}>Customer <Text style={{ color: colors.muted, fontWeight: "500" }}>(optional)</Text></Text><FlatList horizontal showsHorizontalScrollIndicator={false} data={customers.data ?? []} keyExtractor={(item) => String(item.id)} contentContainerStyle={{ gap: 8 }} renderItem={({ item }) => { const active = customerId === item.id; return <Pressable onPress={() => setCustomerId(active ? null : item.id)} style={({ pressed }) => [{ paddingHorizontal: 14, paddingVertical: 10, borderRadius: 17, backgroundColor: active ? colors.primary : colors.background, borderWidth: 1, borderColor: active ? colors.primary : colors.border }, pressed && { opacity: 0.7 }]}><Text style={{ color: active ? "#FFFFFF" : colors.foreground, fontWeight: "700", fontSize: 13 }}>{item.name}</Text></Pressable>; }} /></View>
      <View style={{ borderRadius: 20, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, padding: 16, marginTop: 12 }}><Text style={{ color: colors.foreground, fontSize: 16, fontWeight: "900", marginBottom: 12 }}>Payment method</Text><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>{methods.map((method) => { const active = paymentMethod === method; return <Pressable key={method} onPress={() => setPaymentMethod(method)} style={({ pressed }) => [{ paddingHorizontal: 14, paddingVertical: 10, borderRadius: 17, backgroundColor: active ? colors.primary : colors.background, borderWidth: 1, borderColor: active ? colors.primary : colors.border }, pressed && { opacity: 0.7 }]}><Text style={{ color: active ? "#FFFFFF" : colors.foreground, fontWeight: "700", textTransform: "capitalize", fontSize: 13 }}>{method}</Text></Pressable>; })}</View>{paymentMethod === "cash" && <TextInput value={received} onChangeText={setReceived} keyboardType="decimal-pad" placeholder="Amount received" placeholderTextColor={colors.muted} style={{ marginTop: 12, height: 50, borderRadius: 14, backgroundColor: colors.background, paddingHorizontal: 14, color: colors.foreground, fontSize: 16, fontWeight: "700" }} />}</View>
      <View style={{ marginTop: 18, gap: 12 }}><View className="flex-row justify-between"><Text style={{ color: colors.muted, fontSize: 15 }}>Total</Text><Text style={{ color: colors.foreground, fontSize: 22, fontWeight: "900" }}>{money(cart.total)}</Text></View>{paymentMethod === "cash" && <View className="flex-row justify-between"><Text style={{ color: colors.muted, fontSize: 15 }}>Change due</Text><Text style={{ color: change > 0 ? colors.primary : colors.muted, fontSize: 16, fontWeight: "800" }}>{money(change)}</Text></View>}</View>
      <Pressable disabled={!canSubmit || checkout.isPending} onPress={() => checkout.mutate()} style={({ pressed }) => [{ height: 58, borderRadius: 18, backgroundColor: canSubmit ? colors.primary : colors.border, alignItems: "center", justifyContent: "center", marginTop: 20, shadowColor: colors.primary, shadowOpacity: canSubmit ? 0.18 : 0, shadowRadius: 10, elevation: canSubmit ? 3 : 0 }, pressed && canSubmit && { opacity: 0.86, transform: [{ scale: 0.985 }] }]}><Text style={{ color: "#FFFFFF", fontWeight: "900", fontSize: 16 }}>{checkout.isPending ? "Processing…" : "Complete sale"}</Text></Pressable>
    </ScrollView>
  </ScreenContainer>;
}
