import { useState } from "react";
import { Alert, FlatList, KeyboardAvoidingView, Modal, Platform, Pressable, RefreshControl, Text, TextInput, View } from "react-native";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { portal } from "@/lib/portal";
import { useColors } from "@/hooks/use-colors";
import { LoadingButton } from "@/components/form-feedback";

const avatarColors = ["#0B8AA8", "#243B6B", "#C16D4B", "#6B5CA5"];

export default function Customers() {
  const colors = useColors(); const client = useQueryClient(); const [search, setSearch] = useState(""); const [showCreate, setShowCreate] = useState(false); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [phone, setPhone] = useState("");
  const context = useQuery({ queryKey: ["tenant-context"], queryFn: portal.tenantContext, retry: false });
  const q = useQuery({ queryKey: ["customers", search], queryFn: () => portal.customers({ search: search.trim() || undefined }), enabled: context.isSuccess });
  const create = useMutation({ mutationFn: () => portal.createCustomer({ name: name.trim(), email: email.trim() || null, phone: phone.trim() || null }), onSuccess: () => { setName(""); setEmail(""); setPhone(""); setShowCreate(false); client.invalidateQueries({ queryKey: ["customers"] }); Alert.alert("Customer added", "The customer is now synchronized with the portal."); }, onError: (error) => Alert.alert("Could not add customer", error.message) });
  const errorMessage = q.error instanceof Error ? q.error.message : context.error instanceof Error ? context.error.message : "Unable to load customers.";
  const customers = q.data ?? [];
  const fieldStyle = { height: 50, borderRadius: 14, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 14, color: colors.foreground, marginTop: 10 } as const;
  const closeCreate = () => { setShowCreate(false); setName(""); setEmail(""); setPhone(""); };
  return <ScreenContainer className="px-4 pt-4" edges={["top", "bottom", "left", "right"]}>
    <View style={{ flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 18 }}><View style={{ flex: 1, paddingRight: 14 }}><Text style={{ color: colors.foreground, fontSize: 30, lineHeight: 34, fontWeight: "900", letterSpacing: -0.8 }}>Customers</Text><Text style={{ color: colors.muted, fontSize: 13, marginTop: 4 }}>Your customer directory</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Add customer" onPress={() => setShowCreate(true)} style={({ pressed }) => [{ width: 44, height: 44, borderRadius: 22, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center", shadowColor: colors.primary, shadowOpacity: 0.2, shadowRadius: 8, elevation: 3 }, pressed && { opacity: 0.72, transform: [{ scale: 0.96 }] }]}><IconSymbol name="plus" size={23} color="#FFFFFF" /></Pressable></View>
    <View style={{ height: 52, borderRadius: 17, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, flexDirection: "row", alignItems: "center", paddingHorizontal: 14, marginBottom: 14 }}><IconSymbol name="search.fill" size={20} color={colors.muted} /><TextInput value={search} onChangeText={setSearch} autoCorrect={false} placeholder="Search by name, email, or phone" placeholderTextColor={colors.muted} style={{ flex: 1, marginLeft: 10, color: colors.foreground, fontSize: 14 }} returnKeyType="search" /></View>
    {context.isError || q.isError ? <View style={{ borderRadius: 18, padding: 15, backgroundColor: "#FCEAEA", borderWidth: 1, borderColor: "#F7CACA", marginBottom: 12 }}><View style={{ flexDirection: "row", alignItems: "center", gap: 8 }}><IconSymbol name="checkmark.circle.fill" size={18} color={colors.error} /><Text style={{ color: colors.error, fontWeight: "900" }}>Customer sync unavailable</Text></View><Text style={{ color: colors.error, marginTop: 6, fontSize: 13, lineHeight: 19 }}>{errorMessage}</Text><Pressable onPress={() => { context.refetch(); q.refetch(); }} style={({ pressed }) => [{ marginTop: 11, alignSelf: "flex-start", paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, backgroundColor: "#FFFFFF" }, pressed && { opacity: 0.7 }]}><Text style={{ color: colors.error, fontWeight: "900", fontSize: 12 }}>Retry sync</Text></Pressable></View> : null}
    <View style={{ flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10 }}><Text style={{ color: colors.foreground, fontWeight: "900", fontSize: 15 }}>{q.isLoading ? "Loading directory…" : `${customers.length} ${customers.length === 1 ? "customer" : "customers"}`}</Text><Text style={{ color: colors.muted, fontSize: 12 }}>Live portal data</Text></View>
    <FlatList data={customers} keyExtractor={(x) => String(x.id)} refreshControl={<RefreshControl refreshing={q.isFetching} onRefresh={() => q.refetch()} tintColor={colors.primary} />} showsVerticalScrollIndicator={false} contentContainerStyle={{ gap: 10, paddingBottom: 130 }} renderItem={({ item, index }) => { const initials = item.name.trim().split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); const contact = item.email || item.phone || "No contact details"; return <View style={{ borderRadius: 20, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, padding: 15, shadowColor: "#0E1B3A", shadowOpacity: 0.04, shadowRadius: 10, elevation: 1 }}><View style={{ flexDirection: "row", alignItems: "center" }}><View style={{ width: 48, height: 48, borderRadius: 16, backgroundColor: avatarColors[index % avatarColors.length], alignItems: "center", justifyContent: "center", marginRight: 12 }}><Text style={{ color: "#FFFFFF", fontSize: 16, fontWeight: "900" }}>{initials || "?"}</Text></View><View style={{ flex: 1 }}><Text style={{ color: colors.foreground, fontSize: 16, fontWeight: "900" }} numberOfLines={1}>{item.name}</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 4 }} numberOfLines={1}>{contact}</Text></View><IconSymbol name="chevron.right" size={20} color={colors.muted} /></View><View style={{ height: 1, backgroundColor: colors.border, marginVertical: 13 }} /><View style={{ flexDirection: "row", alignItems: "center", gap: 7 }}><IconSymbol name={item.email ? "paperplane.fill" : "person.fill"} size={15} color={colors.primary} /><Text style={{ color: colors.muted, fontSize: 12 }}>{item.email ? "Email contact" : item.phone ? "Phone contact" : "Contact not provided"}</Text></View></View>; }} ListEmptyComponent={!context.isError && !q.isError ? <View style={{ alignItems: "center", paddingVertical: 58, paddingHorizontal: 24 }}><View style={{ width: 64, height: 64, borderRadius: 22, backgroundColor: "#E6F6F7", alignItems: "center", justifyContent: "center", marginBottom: 14 }}><IconSymbol name="customers.fill" size={29} color={colors.primary} /></View><Text style={{ color: colors.foreground, fontWeight: "900", fontSize: 16 }}>{context.isLoading || q.isLoading ? "Loading customers…" : search ? "No matching customers" : "No customers yet"}</Text><Text style={{ color: colors.muted, textAlign: "center", fontSize: 13, lineHeight: 19, marginTop: 6 }}>{search ? "Try a different name, email, or phone number." : "Add your first customer to begin building the directory."}</Text></View> : null} />
    <Modal visible={showCreate} transparent animationType="slide" onRequestClose={closeCreate}><View style={{ flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(14,27,58,0.32)" }}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : "height"}><View style={{ backgroundColor: colors.surface, borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 20, paddingBottom: 30 }}><View style={{ flexDirection: "row", alignItems: "center", justifyContent: "space-between" }}><View><Text style={{ color: colors.foreground, fontSize: 22, fontWeight: "900" }}>Add customer</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 3 }}>Create a synced portal record</Text></View><Pressable onPress={closeCreate} hitSlop={8}><Text style={{ color: colors.muted, fontSize: 25 }}>×</Text></Pressable></View><TextInput value={name} onChangeText={setName} placeholder="Full name" placeholderTextColor={colors.muted} style={fieldStyle} returnKeyType="next" /><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Email (optional)" placeholderTextColor={colors.muted} style={fieldStyle} returnKeyType="next" /><TextInput value={phone} onChangeText={setPhone} keyboardType="phone-pad" placeholder="Phone (optional)" placeholderTextColor={colors.muted} style={fieldStyle} /><View style={{ flexDirection: "row", gap: 10, marginTop: 16 }}><Pressable onPress={closeCreate} style={{ flex: 1, height: 52, borderRadius: 15, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" }}><Text style={{ color: colors.foreground, fontWeight: "800" }}>Cancel</Text></Pressable><LoadingButton label="Save customer" loadingLabel="Saving…" loading={create.isPending} disabled={!name.trim()} onPress={() => create.mutate()} /></View></View></KeyboardAvoidingView></View></Modal>
  </ScreenContainer>;
}
