import { useState } from "react";
import { Alert, FlatList, Modal, Pressable, Text, TextInput, View } from "react-native";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ScreenContainer } from "@/components/screen-container";
import { portal } from "@/lib/portal";
import { useColors } from "@/hooks/use-colors";
import { money } from "@/shared/omnipos";

export default function Customers() {
  const colors = useColors();
  const client = useQueryClient();
  const [search, setSearch] = useState("");
  const [showCreate, setShowCreate] = useState(false);
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const context = useQuery({ queryKey: ["tenant-context"], queryFn: portal.tenantContext, retry: false });
  const q = useQuery({ queryKey: ["customers", search], queryFn: () => portal.customers({ search: search.trim() || undefined }), enabled: context.isSuccess });
  const create = useMutation({ mutationFn: () => portal.createCustomer({ name: name.trim(), email: email.trim() || null, phone: phone.trim() || null }), onSuccess: () => { setName(""); setEmail(""); setPhone(""); setShowCreate(false); client.invalidateQueries({ queryKey: ["customers"] }); Alert.alert("Customer added", "The customer is now synchronized with the portal."); }, onError: (error) => Alert.alert("Could not add customer", error.message) });
  const errorMessage = q.error instanceof Error ? q.error.message : context.error instanceof Error ? context.error.message : "Unable to load customers.";
  const fieldStyle = { height: 48, borderRadius: 14, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 14, color: colors.foreground, marginTop: 10 } as const;

  return <ScreenContainer className="px-4 pt-4"><View className="flex-row justify-between items-center mb-4"><View><Text style={{ color: colors.foreground, fontSize: 28, fontWeight: "900", letterSpacing: -0.6 }}>Customers</Text><Text style={{ color: colors.muted, fontSize: 13, marginTop: 2 }}>Directory and loyalty</Text></View><Pressable onPress={() => setShowCreate(true)} style={({ pressed }) => [{ width: 42, height: 42, borderRadius: 21, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" }, pressed && { opacity: 0.7 }]}><Text style={{ color: "#FFFFFF", fontSize: 24, lineHeight: 25 }}>+</Text></Pressable></View><TextInput value={search} onChangeText={setSearch} placeholder="Search customers" placeholderTextColor={colors.muted} style={{ height: 50, borderRadius: 16, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 15, color: colors.foreground, marginBottom: 12 }} />
    {context.isError || q.isError ? <View style={{ borderRadius: 16, padding: 14, backgroundColor: "#FCEAEA", marginBottom: 12 }}><Text style={{ color: colors.error, fontWeight: "800" }}>Customer sync unavailable</Text><Text style={{ color: colors.error, marginTop: 4 }}>{errorMessage}</Text><Pressable onPress={() => { context.refetch(); q.refetch(); }} style={{ marginTop: 10 }}><Text style={{ color: colors.error, fontWeight: "900" }}>Retry</Text></Pressable></View> : null}
    <FlatList data={q.data ?? []} keyExtractor={(x) => String(x.id)} contentContainerStyle={{ gap: 10, paddingBottom: 24 }} refreshing={q.isFetching} onRefresh={() => q.refetch()} renderItem={({ item }) => <View style={{ borderRadius: 18, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, padding: 15, shadowColor: "#0E1B3A", shadowOpacity: 0.04, shadowRadius: 8, elevation: 1 }}><View className="flex-row justify-between"><View className="flex-1"><Text style={{ color: colors.foreground, fontWeight: "800", fontSize: 15 }}>{item.name}</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 4 }}>{item.email || item.phone || "No contact details"}</Text></View><Text style={{ color: colors.primary, fontWeight: "900" }}>{item.loyaltyPoints} pts</Text></View><Text style={{ color: colors.muted, fontSize: 12, marginTop: 10 }}>Total spent: {money(item.totalSpent)}</Text></View>} ListEmptyComponent={!context.isError && !q.isError ? <Text style={{ color: colors.muted, textAlign: "center", paddingVertical: 50 }}>{context.isLoading || q.isLoading ? "Loading customers…" : "No customers found"}</Text> : null} />
    <Modal visible={showCreate} transparent animationType="slide" onRequestClose={() => setShowCreate(false)}><View style={{ flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(14,27,58,0.32)" }}><View style={{ backgroundColor: colors.surface, borderTopLeftRadius: 26, borderTopRightRadius: 26, padding: 20, paddingBottom: 28 }}><View className="flex-row justify-between items-center"><Text style={{ color: colors.foreground, fontSize: 21, fontWeight: "900" }}>Add customer</Text><Pressable onPress={() => setShowCreate(false)}><Text style={{ color: colors.muted, fontSize: 24 }}>×</Text></Pressable></View><TextInput value={name} onChangeText={setName} placeholder="Full name" placeholderTextColor={colors.muted} style={fieldStyle} /><TextInput value={email} onChangeText={setEmail} keyboardType="email-address" placeholder="Email (optional)" placeholderTextColor={colors.muted} style={fieldStyle} /><TextInput value={phone} onChangeText={setPhone} keyboardType="phone-pad" placeholder="Phone (optional)" placeholderTextColor={colors.muted} style={fieldStyle} /><Pressable disabled={!name.trim() || create.isPending} onPress={() => create.mutate()} style={({ pressed }) => [{ height: 54, borderRadius: 16, backgroundColor: name.trim() ? colors.primary : colors.border, alignItems: "center", justifyContent: "center", marginTop: 16 }, pressed && { opacity: 0.85 }]}><Text style={{ color: "#FFFFFF", fontWeight: "900" }}>{create.isPending ? "Saving…" : "Save customer"}</Text></Pressable></View></View></Modal>
  </ScreenContainer>;
}
